import { CATEGORY_INFO, CATEGORY_ORDER } from "./directives"
import { SEVERITY_META, scorePolicy, type Severity } from "./score"
import type { Analysis } from "./types"

const SEV_EMOJI: Record<Severity, string> = {
  critical: "🔴",
  high: "🟠",
  medium: "🟡",
  low: "⚪",
}

const APP_URL = "https://csp-analyser.taufiq-dev.workers.dev"

/** Render a full, shareable analysis as Markdown. */
export function buildMarkdownReport(analysis: Analysis): string {
  const s = scorePolicy(analysis)
  const out: string[] = []

  out.push("# CSP Analysis Report", "")
  out.push(`**Grade: ${s.grade} — ${s.posture}** · ${s.score}/100`, "")
  out.push(`> ${s.blurb}`, "")

  out.push("## Policy", "", "```", analysis.input.trim(), "```", "")

  out.push("## Severity summary", "")
  out.push("| Critical | High | Medium | Low |", "| --- | --- | --- | --- |")
  out.push(`| ${s.counts.critical} | ${s.counts.high} | ${s.counts.medium} | ${s.counts.low} |`, "")

  out.push("## Findings", "")
  if (s.issues.length) {
    for (const i of s.issues) {
      const dir = i.directive ? ` \`${i.directive}\`` : ""
      out.push(`### ${SEV_EMOJI[i.severity]} ${SEVERITY_META[i.severity].label} — ${i.title}${dir}`, "")
      out.push(i.detail, "")
      out.push(`**Fix:** ${i.fix}`, "")
    }
  } else {
    out.push("No weaknesses detected against the hardening checks. ✅", "")
  }
  if (s.wins.length) {
    out.push("**What it gets right:**")
    for (const w of s.wins) out.push(`- ${w}`)
    out.push("")
  }

  out.push("## Directives", "")
  for (const cat of CATEGORY_ORDER) {
    const dirs = analysis.byCategory[cat]
    const active = dirs.filter((d) => d.status !== "unset")
    if (cat === "deprecated" && active.length === 0) continue

    out.push(`### ${CATEGORY_INFO[cat].label}`, "")
    for (const d of active) {
      if (d.status === "explicit") {
        const vals = d.rawValues.length
          ? `\`${d.rawValues.join(" ")}\``
          : "_(empty — blocks everything)_"
        out.push(`- **${d.meta.name}** — Set: ${vals}`)
      } else {
        out.push(`- **${d.meta.name}** — Inherited from \`${d.effectiveFrom}\``)
      }
    }
    const unset = dirs.filter((d) => d.status === "unset").map((d) => d.meta.name)
    if (unset.length) out.push(`- _Not set: ${unset.join(", ")}_`)
    out.push("")
  }

  if (analysis.unknown.length) {
    out.push("## Unrecognised directives", "")
    for (const u of analysis.unknown) out.push(`- \`${u.name} ${u.rawValues.join(" ")}\``)
    out.push("")
  }

  out.push("---", `Generated by [CSP Analyser](${APP_URL})`)
  return out.join("\n")
}
